const express = require('express');
const reportRepo = require('../repos/reportRepo');
const pdf = require('../services/pdfService');
const instrumentRepo = require('../repos/instrumentRepo');
const { requireAuth, requireRole } = require('../middleware/auth');

const router = express.Router();
router.use(requireAuth, requireRole('technician','faculty','admin'));

router.get('/', async (req, res, next) => {
  try {
    const filters = readFilters(req);
    const [rows, instruments] = await Promise.all([
      reportRepo.queryBookings(scopedFilters(req.user, filters)),
      instrumentRepo.listAll(),
    ]);
    res.render('reports/index', {
      title: 'Usage reports',
      filters,
      rows,
      summary: reportRepo.summarize(rows),
      instruments,
    });
  } catch (e) { next(e); }
});

router.get('/pdf', async (req, res, next) => {
  try {
    const filters = readFilters(req);
    const rows = await reportRepo.queryBookings(scopedFilters(req.user, filters));
    pdf.renderUsageReport(res, {
      title: 'Instrument Usage Report',
      filters: humanFilters(filters, req.user),
      rows,
      summary: reportRepo.summarize(rows),
      lab: { name: 'BEST Lab', address: 'BITS Pilani Hyderabad Campus' },
    });
  } catch (e) { next(e); }
});

// ── helpers ──────────────────────────────────────────────────────────────
function readFilters(req) {
  return {
    from:         req.query.from || '',
    to:           req.query.to   || '',
    instrumentId: req.query.instrument_id ? Number(req.query.instrument_id) : null,
    status:       req.query.status || '',
  };
}

// Scope filters by the user's role: technicians see only their instruments;
// faculty/admin see everything.
function scopedFilters(user, filters) {
  if (user.role === 'technician') return { ...filters, technicianId: user.id };
  return filters;
}

function humanFilters(filters, user) {
  return {
    'Date range': (filters.from || '…') + ' → ' + (filters.to || '…'),
    'Instrument': filters.instrumentId || 'all',
    'Status':     filters.status      || 'all',
    'Generated by': `${user.name} (${user.role})`,
  };
}

module.exports = router;
