const PDFDocument = require('pdfkit');
const dayjs = require('dayjs');

function renderUsageReport(res, { title, filters, rows, summary, lab }) {
  const doc = new PDFDocument({ size: 'A4', margin: 36 });
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `inline; filename="cal-usage-report-${dayjs().format('YYYYMMDD-HHmm')}.pdf"`);
  doc.pipe(res);

  // Header band
  doc.rect(36, 36, doc.page.width - 72, 50).fill('#1a56db');
  doc.fillColor('white').fontSize(14).font('Helvetica-Bold').text(lab.name || 'Central Analytical Laboratory', 48, 50);
  doc.fontSize(9).font('Helvetica').text(lab.address || 'BITS Pilani Hyderabad Campus', 48, 68);
  doc.fontSize(9).text('Generated: ' + dayjs().format('DD MMM YYYY, HH:mm'), 0, 68, { align: 'right', width: doc.page.width - 48 });

  doc.moveDown(3);
  doc.fillColor('#0f172a').fontSize(16).font('Helvetica-Bold').text(title, { align: 'left' });
  doc.moveDown(0.3);

  // Filters strip
  const filterText = Object.entries(filters)
    .filter(([_, v]) => v != null && v !== '')
    .map(([k, v]) => `${k}: ${v}`).join('   ·   ');
  if (filterText) {
    doc.fontSize(9).font('Helvetica').fillColor('#64748b').text(filterText);
  }
  doc.moveDown();

  // Summary box
  doc.fillColor('#0f172a').fontSize(10).font('Helvetica-Bold').text('Summary');
  doc.font('Helvetica').fontSize(10).fillColor('#334155');
  doc.text(`Total bookings: ${summary.total}    ·    Active-hours scheduled: ${summary.totalHours}`);
  if (Object.keys(summary.byStatus).length) {
    doc.text('By status: ' + Object.entries(summary.byStatus).map(([k,v]) => `${k}=${v}`).join(', '));
  }
  if (Object.keys(summary.byInstrument).length) {
    doc.text('By instrument: ' + Object.entries(summary.byInstrument).map(([k,v]) => `${k}=${v}`).join(', '));
  }
  doc.moveDown();

  // Table
  const headers = ['Date', 'Time', 'Instrument', 'Student', 'Supervisor', 'Status'];
  const widths  = [70, 70, 95, 110, 100, 75];
  const left = 36;
  const totalW = widths.reduce((a,b) => a+b, 0);

  function drawHeader() {
    doc.font('Helvetica-Bold').fontSize(9).fillColor('white');
    doc.rect(left, doc.y, totalW, 18).fill('#1e293b');
    let x = left + 4;
    const y = doc.y + 5;
    headers.forEach((h, i) => { doc.fillColor('white').text(h, x, y, { width: widths[i] - 6 }); x += widths[i]; });
    doc.y += 18;
  }
  drawHeader();

  doc.font('Helvetica').fontSize(8.5).fillColor('#0f172a');
  let zebra = false;
  for (const r of rows) {
    if (doc.y > doc.page.height - 60) {
      doc.addPage();
      drawHeader();
      doc.font('Helvetica').fontSize(8.5).fillColor('#0f172a');
    }
    const rowHeight = 16;
    if (zebra) { doc.rect(left, doc.y, totalW, rowHeight).fill('#f1f5f9'); doc.fillColor('#0f172a'); }
    zebra = !zebra;
    let x = left + 4;
    const y = doc.y + 4;
    const cols = [
      dayjs(r.starts_at).format('DD MMM YY'),
      `${dayjs(r.starts_at).format('HH:mm')}–${dayjs(r.ends_at).format('HH:mm')}`,
      `${r.instrument_code} ${r.instrument_name}`,
      r.student_name,
      r.supervisor_name || '—',
      r.status.replace('_',' '),
    ];
    cols.forEach((c, i) => { doc.text(String(c), x, y, { width: widths[i] - 6, ellipsis: true }); x += widths[i]; });
    doc.y += rowHeight;
  }

  doc.moveDown(2);
  doc.fontSize(8).fillColor('#94a3b8').text('This report is system-generated by the CAL booking portal.', { align: 'center' });

  doc.end();
}

module.exports = { renderUsageReport };
